language: ruby

gemfile:
  - Gemfile

rvm:
  - 2.1.0
  - 2.2.0
  - ruby-head

sudo: false

script:
  - bundle install
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec rake db:test
  - bundle exec rake db:migrate
  - bundle exec rake db:rollback

notifications:
  email:
    - buughost+travis@gmail.com
  irc:
    channels:
      - "irc.esper.net#zarthus"
      - "irc.esper.net#ircgames.dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}) %{author}: %{message} - %{build_url}"
  on_failure: always
  on_success: change
