module GameBot
  VERSION_MAJOR = 0
  VERSION_MINOR = 1
  VERSION_BUILD = 0
  VERSION_APPEND = ''

  VERSION = "#{VERSION_MAJOR}.#{VERSION_MINOR}.#{VERSION_BUILD}#{VERSION_APPEND}".freeze
  USER_AGENT = "GamesBot/#{VERSION} (Net::HTTP, #{RUBY_DESCRIPTION})".freeze
end
